---

name: Elixir Dependency Version Check

on: [pull_request, push]

jobs:
  elixir_deps_check:
    runs-on: ubuntu-20.04
    container: ghcr.io/emqx/emqx-builder/5.0-10:1.13.3-24.2.1-1-ubuntu20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: ensure rebar
        run: ./scripts/ensure-rebar3.sh 3.16.1-emqx-1
      - name: setup mix
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      - name: check elixir deps
        run: ./scripts/check-elixir-deps-discrepancies.exs

...
